INSERT INTO Gioco (Titolo, Descrizione, Immagine, Prezzo , Icon , Approvato, ID_Utente)
VALUES ('Iron Marines', 'Un gioco di strategia in tempo reale che ti porterà alla scoperta di pianeti sconosciuti. Grafica accattivante e con un pizzico di sano humour. Soldati coraggiosi e potenti alieni aspettano i tuoi ordini per affrontare insieme le sfide più grandi.', 'https://cdn.xdroidapps.com/wp-content/uploads/2019/11/Iron-Marines-Cover.jpg', '5.99', "https://img.tuttoandroid.net/wp-content/uploads/2018/07/Brawl-Stars.png", 1, 1);
INSERT INTO Gioco (Titolo, Descrizione, Immagine, Prezzo , Icon , Approvato, ID_Utente)
VALUES ('Burraco', "Scarica gratis il più giocato e completo gioco di carte online di Burraco, l'unico gioco di Burraco con regolamento italiano e con diverse modalità di partita, scelta del numero di giocatori, premi e puntate, grafica in orizzontale e verticale!", 'https://i.ytimg.com/vi/nxEpWhf9zV8/maxresdefault.jpg', '1.99', "https://img.tuttoandroid.net/wp-content/uploads/2018/07/Brawl-Stars.png", 1, 1);
INSERT INTO Gioco (Titolo, Descrizione, Immagine, Prezzo , Icon , Approvato, ID_Utente)
VALUES ('Call of Duty: Mobile', 'Gioco ufficiale di CALL OF DUTY® progettato esclusivamente per dispositivi mobile. Gioca con modalità e mappe multigiocatore iconiche quando vuoi.', 'https://sm.ign.com/ign_it/screenshot/default/vtn2hdrxvjx31-rr4c_btd4.jpg', '4.20', "https://img.tuttoandroid.net/wp-content/uploads/2018/07/Brawl-Stars.png", 1, 1);
INSERT INTO Gioco (Titolo, Descrizione, Immagine, Prezzo, Icon , Approvato, ID_Utente)
VALUES ('Candy Crush Saga', 'Inizia a giocare oggi stesso a Candy Crush Saga: un rompicapo leggendario che piace a milioni di giocatori in tutto il mondo.', 'https://www.xn--cos-8la.com/wp/wp-content/uploads/2013/07/CANDY-CRUSH.jpg', '2.99', "https://img.tuttoandroid.net/wp-content/uploads/2018/07/Brawl-Stars.png", 1, 1);
INSERT INTO Gioco (Titolo, Descrizione, Immagine, Prezzo, Icon, Approvato, ID_Utente)
VALUES ('Kingdom Rush', 'Preparati per un viaggio epico per difendere il tuo regno da orde di orchi, troll, maghi malvagi e altri cattivi demoni usando un vasto arsenale di torri e incantesimi al tuo comando!', 'https://cdn-ext.fanatical.com/production/product/original/b6ecaef8-6a2c-484d-89fe-9a55ea091d1e.jpeg?w=1200', '3.99', "https://img.tuttoandroid.net/wp-content/uploads/2018/07/Brawl-Stars.png",1 ,1);
